<?php

namespace App\Helper;

class FideFederationHelper
{
    /** @var array<string, string> ISO 3166-1 alpha-2 (lowercase) => código FIDE */
    private const ALPHA2_TO_CODE = [
        'af' => 'AFG', 'al' => 'ALB', 'dz' => 'ALG', 'ad' => 'AND', 'ao' => 'ANG',
        'ag' => 'ANT', 'ar' => 'ARG', 'am' => 'ARM', 'aw' => 'ARU', 'au' => 'AUS',
        'at' => 'AUT', 'az' => 'AZE', 'bs' => 'BAH', 'bd' => 'BAN', 'bb' => 'BAR',
        'bi' => 'BDI', 'be' => 'BEL', 'bm' => 'BER', 'bt' => 'BHU', 'ba' => 'BIH',
        'bz' => 'BIZ', 'by' => 'BLR', 'bo' => 'BOL', 'bw' => 'BOT', 'br' => 'BRA',
        'bh' => 'BRN', 'bn' => 'BRU', 'bg' => 'BUL', 'bf' => 'BUR', 'cf' => 'CAF',
        'kh' => 'CAM', 'ca' => 'CAN', 'ky' => 'CAY', 'cg' => 'CGO', 'td' => 'CHA',
        'cl' => 'CHI', 'cn' => 'CHN', 'ci' => 'CIV', 'cm' => 'CMR', 'cd' => 'COD',
        'co' => 'COL', 'km' => 'COM', 'cv' => 'CPV', 'cr' => 'CRC', 'hr' => 'CRO',
        'cu' => 'CUB', 'cw' => 'CUR', 'cy' => 'CYP', 'cz' => 'CZE', 'dk' => 'DEN',
        'dj' => 'DJI', 'dm' => 'DMA', 'do' => 'DOM', 'ec' => 'ECU', 'eg' => 'EGY',
        'er' => 'ERI', 'sv' => 'ESA', 'es' => 'ESP', 'ee' => 'EST', 'et' => 'ETH',
        'fo' => 'FAI', 'fj' => 'FIJ', 'fi' => 'FIN', 'fr' => 'FRA', 'ga' => 'GAB',
        'gm' => 'GAM', 'gg' => 'GCI', 'ge' => 'GEO', 'gq' => 'GEQ', 'de' => 'GER',
        'gh' => 'GHA', 'gr' => 'GRE', 'gl' => 'GRL', 'gd' => 'GRN', 'gt' => 'GUA',
        'gn' => 'GUI', 'gu' => 'GUM', 'gy' => 'GUY', 'ht' => 'HAI', 'hk' => 'HKG',
        'hn' => 'HON', 'hu' => 'HUN', 'id' => 'INA', 'in' => 'IND', 'im' => 'IOM',
        'ir' => 'IRI', 'ie' => 'IRL', 'iq' => 'IRQ', 'is' => 'ISL', 'il' => 'ISR',
        'vi' => 'ISV', 'it' => 'ITA', 'vg' => 'IVB', 'jm' => 'JAM', 'je' => 'JCI',
        'jo' => 'JOR', 'jp' => 'JPN', 'kz' => 'KAZ', 'ke' => 'KEN', 'kg' => 'KGZ',
        'ki' => 'KIR', 'kr' => 'KOR', 'sa' => 'KSA', 'kw' => 'KUW', 'la' => 'LAO',
        'lv' => 'LAT', 'ly' => 'LBA', 'lb' => 'LBN', 'lr' => 'LBR', 'lc' => 'LCA',
        'ls' => 'LES', 'li' => 'LIE', 'lt' => 'LTU', 'lu' => 'LUX', 'mo' => 'MAC',
        'mg' => 'MAD', 'ma' => 'MAR', 'my' => 'MAS', 'mw' => 'MAW', 'md' => 'MDA',
        'mv' => 'MDV', 'mx' => 'MEX', 'mn' => 'MGL', 'mh' => 'MHL', 'mk' => 'MKD',
        'ml' => 'MLI', 'mt' => 'MLT', 'mc' => 'MNC', 'me' => 'MNE', 'mz' => 'MOZ',
        'mu' => 'MRI', 'mr' => 'MTN', 'mm' => 'MYA', 'na' => 'NAM', 'ni' => 'NCA',
        'nc' => 'NCL', 'nl' => 'NED', 'np' => 'NEP', 'ng' => 'NGR', 'ne' => 'NIG',
        'no' => 'NOR', 'nr' => 'NRU', 'nz' => 'NZL', 'om' => 'OMA', 'pk' => 'PAK',
        'pa' => 'PAN', 'py' => 'PAR', 'pe' => 'PER', 'ph' => 'PHI', 'ps' => 'PLE',
        'pw' => 'PLW', 'pg' => 'PNG', 'pl' => 'POL', 'pt' => 'POR', 'pr' => 'PUR',
        'qa' => 'QAT', 'ro' => 'ROU', 'za' => 'RSA', 'ru' => 'RUS', 'rw' => 'RWA',
        'sn' => 'SEN', 'sc' => 'SEY', 'sg' => 'SGP', 'kn' => 'SKN', 'sl' => 'SLE',
        'si' => 'SLO', 'sm' => 'SMR', 'sb' => 'SOL', 'so' => 'SOM', 'rs' => 'SRB',
        'lk' => 'SRI', 'ss' => 'SSD', 'st' => 'STP', 'sd' => 'SUD', 'ch' => 'SUI',
        'sr' => 'SUR', 'sk' => 'SVK', 'se' => 'SWE', 'sz' => 'SWZ', 'sy' => 'SYR',
        'tz' => 'TAN', 'to' => 'TGA', 'th' => 'THA', 'tj' => 'TJK', 'tm' => 'TKM',
        'tl' => 'TLS', 'tg' => 'TOG', 'tt' => 'TTO', 'tn' => 'TUN', 'tr' => 'TUR',
        'ae' => 'UAE', 'ug' => 'UGA', 'ua' => 'UKR', 'uy' => 'URU', 'us' => 'USA',
        'uz' => 'UZB', 'vu' => 'VAN', 've' => 'VEN', 'vn' => 'VIE', 'vc' => 'VIN',
        'ye' => 'YEM', 'zm' => 'ZAM', 'zw' => 'ZIM',
    ];

    /** @var array<string, string> Nome da federação (FIDE) => código FIDE */
    private const NAME_TO_CODE = [
        'Afghanistan' => 'AFG',
        'Netherlands Antilles' => 'AHO',
        'Albania' => 'ALB',
        'Algeria' => 'ALG',
        'Andorra' => 'AND',
        'Angola' => 'ANG',
        'Antigua and Barbuda' => 'ANT',
        'Argentina' => 'ARG',
        'Armenia' => 'ARM',
        'Aruba' => 'ARU',
        'Australia' => 'AUS',
        'Austria' => 'AUT',
        'Azerbaijan' => 'AZE',
        'Bahamas' => 'BAH',
        'Bangladesh' => 'BAN',
        'Barbados' => 'BAR',
        'Burundi' => 'BDI',
        'Belgium' => 'BEL',
        'Bermuda' => 'BER',
        'Bhutan' => 'BHU',
        'Bosnia & Herzegovina' => 'BIH',
        'Bosnia and Herzegovina' => 'BIH',
        'Belize' => 'BIZ',
        'Belarus' => 'BLR',
        'Bolivia' => 'BOL',
        'Botswana' => 'BOT',
        'Brazil' => 'BRA',
        'Bahrain' => 'BRN',
        'Brunei Darussalam' => 'BRU',
        'Brunei' => 'BRU',
        'Bulgaria' => 'BUL',
        'Burkina Faso' => 'BUR',
        'Central African Republic' => 'CAF',
        'Cambodia' => 'CAM',
        'Canada' => 'CAN',
        'Cayman Islands' => 'CAY',
        'Congo' => 'CGO',
        'Chad' => 'CHA',
        'Chile' => 'CHI',
        'China' => 'CHN',
        'Cote d\'Ivoire' => 'CIV',
        'Ivory Coast' => 'CIV',
        'Cameroon' => 'CMR',
        'Democratic Republic of the Congo' => 'COD',
        'Colombia' => 'COL',
        'Comoros Islands' => 'COM',
        'Comoros' => 'COM',
        'Cape Verde' => 'CPV',
        'Costa Rica' => 'CRC',
        'Croatia' => 'CRO',
        'Cuba' => 'CUB',
        'Curacao' => 'CUR',
        'Curaçao' => 'CUR',
        'Cyprus' => 'CYP',
        'Czech Republic' => 'CZE',
        'Denmark' => 'DEN',
        'Djibouti' => 'DJI',
        'Dominica' => 'DMA',
        'Dominican Republic' => 'DOM',
        'Ecuador' => 'ECU',
        'Egypt' => 'EGY',
        'England' => 'ENG',
        'Eritrea' => 'ERI',
        'El Salvador' => 'ESA',
        'Spain' => 'ESP',
        'Estonia' => 'EST',
        'Ethiopia' => 'ETH',
        'Faroe Islands' => 'FAI',
        'FIDE' => 'FID',
        'Fiji' => 'FIJ',
        'Finland' => 'FIN',
        'France' => 'FRA',
        'Gabon' => 'GAB',
        'Gambia' => 'GAM',
        'Guernsey' => 'GCI',
        'Georgia' => 'GEO',
        'Equatorial Guinea' => 'GEQ',
        'Germany' => 'GER',
        'Ghana' => 'GHA',
        'Greece' => 'GRE',
        'Greenland' => 'GRL',
        'Grenada' => 'GRN',
        'Guatemala' => 'GUA',
        'Guinea' => 'GUI',
        'Guam' => 'GUM',
        'Guyana' => 'GUY',
        'Haiti' => 'HAI',
        'Hong Kong, China' => 'HKG',
        'Hong Kong' => 'HKG',
        'Honduras' => 'HON',
        'Hungary' => 'HUN',
        'Indonesia' => 'INA',
        'India' => 'IND',
        'Isle of Man' => 'IOM',
        'Iran' => 'IRI',
        'Ireland' => 'IRL',
        'Iraq' => 'IRQ',
        'Iceland' => 'ISL',
        'Israel' => 'ISR',
        'US Virgin Islands' => 'ISV',
        'Italy' => 'ITA',
        'British Virgin Islands' => 'IVB',
        'Jamaica' => 'JAM',
        'Jersey' => 'JCI',
        'Jordan' => 'JOR',
        'Japan' => 'JPN',
        'Kazakhstan' => 'KAZ',
        'Kenya' => 'KEN',
        'Kyrgyzstan' => 'KGZ',
        'Kiribati' => 'KIR',
        'South Korea' => 'KOR',
        'Korea' => 'KOR',
        'Kosovo' => 'KOS',
        'Kosovo *' => 'KOS',
        'Saudi Arabia' => 'KSA',
        'Kuwait' => 'KUW',
        'Laos' => 'LAO',
        'Latvia' => 'LAT',
        'Libya' => 'LBA',
        'Lebanon' => 'LBN',
        'Liberia' => 'LBR',
        'Saint Lucia' => 'LCA',
        'Lesotho' => 'LES',
        'Liechtenstein' => 'LIE',
        'Lithuania' => 'LTU',
        'Luxembourg' => 'LUX',
        'Macau' => 'MAC',
        'Madagascar' => 'MAD',
        'Morocco' => 'MAR',
        'Malaysia' => 'MAS',
        'Malawi' => 'MAW',
        'Moldova' => 'MDA',
        'Maldives' => 'MDV',
        'Mexico' => 'MEX',
        'Mongolia' => 'MGL',
        'Marshall Islands' => 'MHL',
        'North Macedonia' => 'MKD',
        'Macedonia' => 'MKD',
        'Mali' => 'MLI',
        'Malta' => 'MLT',
        'Monaco' => 'MNC',
        'Montenegro' => 'MNE',
        'Mozambique' => 'MOZ',
        'Mauritius' => 'MRI',
        'Mauritania' => 'MTN',
        'Myanmar' => 'MYA',
        'Namibia' => 'NAM',
        'Nicaragua' => 'NCA',
        'New Caledonia' => 'NCL',
        'Netherlands' => 'NED',
        'Nepal' => 'NEP',
        'Nigeria' => 'NGR',
        'Niger' => 'NIG',
        'Norway' => 'NOR',
        'Nauru' => 'NRU',
        'New Zealand' => 'NZL',
        'Oman' => 'OMA',
        'Pakistan' => 'PAK',
        'Panama' => 'PAN',
        'Paraguay' => 'PAR',
        'Peru' => 'PER',
        'Philippines' => 'PHI',
        'Palestine' => 'PLE',
        'Palau' => 'PLW',
        'Papua New Guinea' => 'PNG',
        'Poland' => 'POL',
        'Portugal' => 'POR',
        'Puerto Rico' => 'PUR',
        'Qatar' => 'QAT',
        'Romania' => 'ROU',
        'South Africa' => 'RSA',
        'Russia' => 'RUS',
        'Rwanda' => 'RWA',
        'Scotland' => 'SCO',
        'Senegal' => 'SEN',
        'Seychelles' => 'SEY',
        'Singapore' => 'SGP',
        'Saint Kitts and Nevis' => 'SKN',
        'Sierra Leone' => 'SLE',
        'Slovenia' => 'SLO',
        'San Marino' => 'SMR',
        'Solomon Islands' => 'SOL',
        'Somalia' => 'SOM',
        'Serbia' => 'SRB',
        'Sri Lanka' => 'SRI',
        'South Sudan' => 'SSD',
        'Sao Tome and Principe' => 'STP',
        'Sudan' => 'SUD',
        'Switzerland' => 'SUI',
        'Suriname' => 'SUR',
        'Slovakia' => 'SVK',
        'Sweden' => 'SWE',
        'Eswatini' => 'SWZ',
        'Swaziland' => 'SWZ',
        'Syria' => 'SYR',
        'Tanzania' => 'TAN',
        'Tonga' => 'TGA',
        'Thailand' => 'THA',
        'Tajikistan' => 'TJK',
        'Turkmenistan' => 'TKM',
        'Timor-Leste' => 'TLS',
        'Togo' => 'TOG',
        'Chinese Taipei' => 'TPE',
        'Taiwan' => 'TPE',
        'Trinidad and Tobago' => 'TTO',
        'Tunisia' => 'TUN',
        'Turkiye' => 'TUR',
        'Turkey' => 'TUR',
        'United Arab Emirates' => 'UAE',
        'Uganda' => 'UGA',
        'Ukraine' => 'UKR',
        'Uruguay' => 'URU',
        'United States of America' => 'USA',
        'United States' => 'USA',
        'Uzbekistan' => 'UZB',
        'Vanuatu' => 'VAN',
        'Venezuela' => 'VEN',
        'Vietnam' => 'VIE',
        'Saint Vincent and the Grenadines' => 'VIN',
        'Wales' => 'WLS',
        'Yemen' => 'YEM',
        'Zambia' => 'ZAM',
        'Zimbabwe' => 'ZIM',
    ];

    public static function fromAlpha2(?string $alpha2): ?string
    {
        if ($alpha2 === null || $alpha2 === '') {
            return null;
        }

        $alpha2 = strtolower(trim($alpha2));

        return self::ALPHA2_TO_CODE[$alpha2] ?? null;
    }

    public static function fromName(?string $name): ?string
    {
        if ($name === null || trim($name) === '') {
            return null;
        }

        $name = trim($name);

        if (isset(self::NAME_TO_CODE[$name])) {
            return self::NAME_TO_CODE[$name];
        }

        $lower = strtolower($name);
        foreach (self::NAME_TO_CODE as $fedName => $code) {
            if (strtolower($fedName) === $lower) {
                return $code;
            }
        }

        return null;
    }

    public static function resolve(?string $alpha2, ?string $federationName): ?string
    {
        $fromAlpha2 = self::fromAlpha2($alpha2);
        if ($fromAlpha2 !== null) {
            return $fromAlpha2;
        }

        return self::fromName($federationName);
    }
}
