version: '2'
services:
  xadrezsuico:
    image: jppcel/xadrezsuico:20230117-1
    restart: always
    ports:
      - 16001:80
    volumes:
      - ../:/var/www/html
    # command: "bash -c 'cd /var/www/html && composer install' && apache2-foreground"
    # entrypoint: "bash -c 'cd /var/www/html && composer install && php artisan migrate --force' && docker-php-entrypoint"
    environment:
      - APP_ENV=local
      - APP_KEY=base64:qVWMyTVX2qhrg6loaIqxrFYsLmPrixOiOxCtN3269+Q=
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=xadrezsuico
      - DB_USERNAME=root
      - DB_PASSWORD=ca?ePhoj2tho#rokar3cupruspapum
      - QUEUE_CONNECTION=database

  xadrezsuicopag_cron:
    depends_on:
      - xadrezsuicopag
    restart: always
    build:
      context: ./../../../xadrezsuicopag-docker
      dockerfile: Dockerfile-cron
    volumes:
      - ../../../xadrezsuico-pagamento:/var/www/html
    environment:
      - APP_ENV=local
      - APP_KEY=base64:qVWMyTVX2qhrg6loaIqxrFYsLmPrixOiOxCtN3269+Q=
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=xadrezsuicopag
      - DB_USERNAME=root
      - DB_PASSWORD=ca?ePhoj2tho#rokar3cupruspapum
      - QUEUE_CONNECTION=database

  xadrezsuicopag:
    restart: always
    build:
      context: ./../../../xadrezsuicopag-docker
      dockerfile: Dockerfile
    ports:
      - 15002:80
    volumes:
      - ../../../xadrezsuico-pagamento:/var/www/html
    # command: "bash -c 'cd /var/www/html && composer install' && apache2-foreground"
    # entrypoint: "bash -c 'cd /var/www/html && composer install && php artisan migrate --force' && docker-php-entrypoint"
    environment:
      - APP_ENV=local
      - APP_KEY=base64:qVWMyTVX2qhrg6loaIqxrFYsLmPrixOiOxCtN3269+Q=
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=xadrezsuicopag
      - DB_USERNAME=root
      - DB_PASSWORD=ca?ePhoj2tho#rokar3cupruspapum
      - QUEUE_CONNECTION=database

  mysql:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=ca?ePhoj2tho#rokar3cupruspapum
      - MYSQL_USER=fexpar_arbitro
      - MYSQL_DATABASE=xadrezsuico
      - MYSQL_PASSWORD=qabraQawro-ath9hU#pl
      - TZ=America/Sao_Paulo
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3312:3306
    entrypoint:
      sh -c "echo 'CREATE DATABASE IF NOT EXISTS xadrezsuico;' > /docker-entrypoint-initdb.d/init.sql; /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
